In [5]:
import pandas

In [6]:
mergedData = pandas.read_csv('Merged_Data.csv')
mergedData

,month,year,City Name,Province,Lat,Lng,mean_2m_air_temperature,total_precipitation,Above 2500,Below 40,All Elevation,premWater,area,flooded
0,2,2003,Badin,Sindh,24.763178,68.827560,295.028687,0.006125,0.000000,7286.466667,7286.466667,213100.172549,6.604870e+09,YES
1,2,2003,Central Karachi,Sindh,24.947833,67.060062,295.255163,0.003351,0.000000,37.254902,70.121569,2.027451,6.348250e+07,NO
2,2,2003,Dadu,Sindh,26.751405,67.527545,292.585169,0.004867,0.000000,1111.360784,9123.356863,160051.650980,8.121250e+09,YES
3,2,2003,East Karachi,Sindh,24.930772,67.160347,295.252340,0.003351,0.000000,91.333333,226.333333,85.196078,2.047757e+08,NO
4,2,2003,Ghotki,Sindh,27.830511,69.696524,292.045874,0.021952,0.000000,0.000000,7352.356863,57589.423529,6.488814e+09,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,7,2018,Swat,Khyber Pakhtunkhwa,35.232475,72.511635,288.543267,0.144815,3778.803922,0.000000,6619.125490,13968.298039,5.393805e+09,YES
3996,7,2018,Tank,Khyber Pakhtunkhwa,32.317156,70.375392,302.578444,0.189258,0.000000,0.000000,3400.717647,7402.411765,2.867340e+09,NO
3997,7,2018,Upper Dir,Khyber Pakhtunkhwa,35.405002,72.114440,290.037942,0.092807,1998.490196,0.000000,3223.623529,1572.396078,2.622859e+09,YES
3998,7,2018,Upper Kohistan,Khyber Pakhtunkhwa,35.423048,73.221918,287.044568,0.112655,5221.427451,0.000000,6641.898039,7520.270588,5.401930e+09,YES
3999,7,2018,Kolai-Palas,Khyber Pakhtunkhwa,35.066544,73.249767,289.596121,0.163310,990.988235,0.000000,1441.137255,1763.713725,1.177753e+09,NO

In [7]:
# Calculate the percentages
mergedData['Above 2500_percentage'] = (mergedData['Above 2500'] / mergedData['All Elevation']) * 100
mergedData['Below 118_percentage'] = (mergedData['Below 40'] / mergedData['All Elevation']) * 100

mergedData

,month,year,City Name,Province,Lat,Lng,mean_2m_air_temperature,total_precipitation,Above 2500,Below 40,All Elevation,premWater,area,flooded,Above 2500_percentage,Below 118_percentage
0,2,2003,Badin,Sindh,24.763178,68.827560,295.028687,0.006125,0.000000,7286.466667,7286.466667,213100.172549,6.604870e+09,YES,0.000000,100.000000
1,2,2003,Central Karachi,Sindh,24.947833,67.060062,295.255163,0.003351,0.000000,37.254902,70.121569,2.027451,6.348250e+07,NO,0.000000,53.129020
2,2,2003,Dadu,Sindh,26.751405,67.527545,292.585169,0.004867,0.000000,1111.360784,9123.356863,160051.650980,8.121250e+09,YES,0.000000,12.181490
3,2,2003,East Karachi,Sindh,24.930772,67.160347,295.252340,0.003351,0.000000,91.333333,226.333333,85.196078,2.047757e+08,NO,0.000000,40.353461
4,2,2003,Ghotki,Sindh,27.830511,69.696524,292.045874,0.021952,0.000000,0.000000,7352.356863,57589.423529,6.488814e+09,YES,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,7,2018,Swat,Khyber Pakhtunkhwa,35.232475,72.511635,288.543267,0.144815,3778.803922,0.000000,6619.125490,13968.298039,5.393805e+09,YES,57.089172,0.000000
3996,7,2018,Tank,Khyber Pakhtunkhwa,32.317156,70.375392,302.578444,0.189258,0.000000,0.000000,3400.717647,7402.411765,2.867340e+09,NO,0.000000,0.000000
3997,7,2018,Upper Dir,Khyber Pakhtunkhwa,35.405002,72.114440,290.037942,0.092807,1998.490196,0.000000,3223.623529,1572.396078,2.622859e+09,YES,61.995149,0.000000
3998,7,2018,Upper Kohistan,Khyber Pakhtunkhwa,35.423048,73.221918,287.044568,0.112655,5221.427451,0.000000,6641.898039,7520.270588,5.401930e+09,YES,78.613484,0.000000
3999,7,2018,Kolai-Palas,Khyber Pakhtunkhwa,35.066544,73.249767,289.596121,0.163310,990.988235,0.000000,1441.137255,1763.713725,1.177753e+09,NO,68.764320,0.000000